export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST"
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS"
export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL"

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST"
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS"
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL"

export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST"
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS"
export const BLOG_CREATE_FAIL = "BLOG_CREATE_FAIL"

export const USER_BLOGS_REQUEST = "USER_BLOGS_REQUEST"
export const USER_BLOGS_SUCCESS = "USER_BLOGS_SUCCESS"
export const USER_BLOGS_FAIL = "USER_BLOGS_FAIL"

export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST"
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS"
export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL"

export const BLOG_EDIT_REQUEST = "BLOG_EDIT_REQUEST"
export const BLOG_EDIT_SUCCESS = "BLOG_EDIT_SUCCESS"
export const BLOG_EDIT_FAIL = "BLOG_EDIT_FAIL"